<a href="https://colab.research.google.com/github/HK-hy3/Basic-Linear-Algebra/blob/main/DS_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import det, inv, orth

In [2]:
# --- Q1: Matrix Operations ---
A = np.array([[2, 4], [3, 5]])
B = np.array([[1, 2], [2, 3]])

# Addition
add_result = A + B

# Subtraction
sub_result = A - B

# Matrix Multiplication
mul_result = np.dot(A, B)

# Element-wise Multiplication
elem_mul_result = A * B

# Determinant
det_A = det(A)

# Inverse
inv_A = inv(A)

print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)
print("Matrix Multiplication:\n", mul_result)
print("Element-wise Multiplication:\n", elem_mul_result)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)


Addition:
 [[3 6]
 [5 8]]
Subtraction:
 [[1 2]
 [1 2]]
Matrix Multiplication:
 [[10 16]
 [13 21]]
Element-wise Multiplication:
 [[ 2  8]
 [ 6 15]]
Determinant of A: -2.0
Inverse of A:
 [[-2.5  2. ]
 [ 1.5 -1. ]]


In [6]:
# --- Q2: Eigenvalues & Eigenvectors ---
eigenvalues, eigenvectors = np.linalg.eig(A)

# Check orthogonality
orthogonality_check = np.dot(eigenvectors.T, eigenvectors)

print("Eigenvalues of A:\n", eigenvalues)  # Printing only eigenvalues
print("Eigenvectors of A:\n", eigenvectors)
print("Orthogonality Check (should be identity matrix):\n", orthogonality_check)

if np.allclose(orthogonality_check, np.eye(eigenvectors.shape[1])):
    print("Eigenvectors are orthogonal.")
else:
    print("Eigenvectors are not orthogonal.")

Eigenvalues of A:
 [-0.27491722  7.27491722]
Eigenvectors of A:
 [[-0.86925207 -0.60422718]
 [ 0.49436913 -0.79681209]]
Orthogonality Check (should be identity matrix):
 [[1.         0.13130643]
 [0.13130643 1.        ]]
Eigenvectors are not orthogonal.


In [8]:
# --- Q3: Span and Basis ---

# Define a set of vectors (rows represent vectors)
V = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])

# Compute the basis (orthonormal basis using QR decomposition)
basis = orth(V)

# Span explanation
span_dim = np.linalg.matrix_rank(V)  # The dimension of the span

print("Original Set of Vectors:\n", V)
print("Basis of the Vector Space:\n", basis)
print(f"Dimension of the Span: {span_dim}")


Original Set of Vectors:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
Basis of the Vector Space:
 [[-0.26726124]
 [-0.53452248]
 [-0.80178373]]
Dimension of the Span: 1
